### ISSUE TITLE
API endpoint to find/fetch a standard document 

### ISSUE THREAD

**Issue by abunashir** [relaton/api.relaton.org#2]
The relaton service should be able to return any document from the supported standards. Here are the requirements to fetch a document, let's say the endpoint is `/documents/find`.

* Give me a document with a name,  eg: `/find?name=ISO_19011`
* Give me a document with a name and year, eg: `/find?name=ISO_19011&year=2011`
* Give me a document within specific format, eg: `/find?name=ISO_19011&format=xml`

@ronaldtse, is there anything else you would like to add here? what would you prefer as default response format?

**Comment by ronaldtse** [comment]
GraphQL, JSON?

**Comment by abunashir** [comment]
Yap, do we also want to return the document in XML (relaton-xml) ?

**Comment by ronaldtse** [comment]
@abunashir certainly! Lower in priority though, since JSON is easier to use for most.

**Comment by abunashir** [comment]
The fetch endpoint is done, by default it will return the document in `JSON`, but user can pass additional parameters if they want it in XML.

Currently, it is only a rest API, but as a next step, we can add the graphql endpoint. cc: @ronaldtse
