### ISSUE TITLE
Migrate the service to AWS Lambda

### ISSUE THREAD

**Issue by abunashir** [relaton/api.relaton.org#20]
We are hosting this service in Heroku at the moment, but as most of our tools/apps are in AWS, so the idea with this issue is to migrate this application to AWS lambda. We should also enable the CI to deploy the master branch automatically.

//cc: @ronaldtse

**Comment by phuonghuynh** [comment]
@ronaldtse @andrew2net AWS Gateway integrate with Lambda using Proxy type, only POST accepted, https://docs.aws.amazon.com/lambda/latest/dg/API_Invoke.html

could we update API to support for POST method only?

**Comment by andrew2net** [comment]
@phuonghuynh I don't see any constraints about using only the POST method in the link you provided. There is an example that uses POST but it doesn't mean we can't use GET.
Using the only POST is against the REST API concept. [Here](https://docs.aws.amazon.com/apigateway/latest/developerguide/api-gateway-create-api-as-simple-proxy-for-lambda.html) there is a description of how to allow any HTTP methods to invoke Lamda function.

> In a proxy integration, the entire request is sent to the backend Lambda function as-is, via a catch-all ANY method that represents any HTTP method. The actual HTTP method is specified by the client at run time. The ANY method allows you to use a single API method setup for all of the supported HTTP methods: DELETE, GET, HEAD, OPTIONS, PATCH, POST, and PUT.

**Comment by phuonghuynh** [comment]
Yep, Gateway will handle ANY method then proxy to POST to lambda

**Comment by ronaldtse** [comment]
Completed.
