### ISSUE TITLE
500 error with 'https://api.relaton.org/api/v1/document?code=ISO%10241-1'

### ISSUE THREAD

**Issue by ronaldtse** [relaton/api.relaton.org#39]
Try: https://api.relaton.org/api/v1/document?code=ISO%10241-1

**Comment by andrew2net** [comment]
@ronaldtse the URL https://api.relaton.org/api/v1/document?code=ISO%10241-1 is incorrect.
It should be https://api.relaton.org/api/v1/document?code=ISO%2010241-1

**Comment by ronaldtse** [comment]
But still it should not return 500. Can you help fix it so it fails gracefully? Thanks.

**Comment by andrew2net** [comment]
It seems AWS CloudFront returns the error. CloudFront tries to parse the URL parameters. Lambda gets parsed parameters in a hash. Maybe @phuonghuynh can check if CloudFront has settings to workaround it.

**Comment by ronaldtse** [comment]
@andrew2net great find, thanks!
