### ISSUE TITLE
Enabled Travis CI / Other automation tool

### ISSUE THREAD

**Issue by abunashir** [relaton/api.relaton.org#4]
Hi @ronaldtse, could you please enable Travis CI and Hound CI for this repo?

**Comment by abunashir** [comment]
I've added a [Github's action](https://github.com/relaton/relaton.org/actions) to run our tests, so we don't need the Travis CI anymore, but @ronaldtse  could you please disable the circus CI for this repo, we actually don't need that test at the moment.

**Comment by ronaldtse** [comment]
Thanks @abunashir ! Travis CI is disabled but I can't find where Cirrus is used here...

**Comment by abunashir** [comment]
Sweet, I will check on that, I think that was being added by some marketplace addon/automation
