### ISSUE TITLE
Regenerate GitHub Action for CI with Push permission

### ISSUE THREAD

**Issue by phuonghuynh** [relaton/api.relaton.org#40]
@ronaldtse GitHub apply new format for its tokens, so we need to update our CI Secrets token or GHA won't work as expected

>  We noticed your personal access token, xxxx, has an outdated format and was used to access the GitHub API xxx

**Comment by ronaldtse** [comment]
There is no deadline for migration so we don't need to do this now.

**Comment by ronaldtse** [comment]
@phuonghuynh which repo are you seeing this? I believe relaton-ci is already using the new token format.

**Comment by phuonghuynh** [comment]
This notice is for my PAT; not CI PAT;

Last 2 GHAs failed on emit event for deploy to lambda, https://github.com/relaton/api.relaton.org/actions/runs/1221395328, so I guess that issue related to GHA CI Token; like my tested Repo Action

**Comment by ronaldtse** [comment]
@phuonghuynh What is the problem here? 

I have re-generated the token, but both the old and new ones already use the new format. The token has full read/write repo/packages access:

<img width="637" alt="Screenshot 2021-10-26 at 12 23 22 AM" src="https://user-images.githubusercontent.com/11865/138733599-c69d31ab-6d87-475d-8ff1-bc18d2ef9df1.png">

**Comment by ronaldtse** [comment]
The secret is called `RELATON_CI_PAT` in all public repositories as well as in infrastructure-lambda-api. Closing this.

**Comment by phuonghuynh** [comment]
@andrew2net could we test new CI token ?

**Comment by andrew2net** [comment]
@phuonghuynh I've tried to run the manual-release workflow twice with API_VERSION: 1.9.1-preview.1 and API_VERSION: 1.9.1-preview.2, GEM_VERSION: 1.9.1 but the on-release workflow isn't triggered.

**Comment by ronaldtse** [comment]
@phuonghuynh could you please help with this task? Thanks.

**Comment by phuonghuynh** [comment]
Yes

**Comment by phuonghuynh** [comment]
@andrew2net could you help to fix GHA build failed because of rspec error?

https://github.com/relaton/api.relaton.org/runs/7592911061?check_suite_focus=true

**Comment by andrew2net** [comment]
@phuonghuynh fixed

**Comment by ronaldtse** [comment]
Ping @phuonghuynh

**Comment by phuonghuynh** [comment]
New GHA working, so I think we can close this issue, https://github.com/relaton/api.relaton.org/actions/runs/2869996420

**Comment by ronaldtse** [comment]
Thanks @phuonghuynh !
